// Code generated by z. DO NOT EDIT.

package zuint64

import "errors"

var (
	ErrInterfaceNotUint64 = errors.New("encountered non-uint64 interface")
)

// Check if a slice ([]uint64) contains a matching member
func Contains(haystack []uint64, needle uint64) bool {
	for _, val := range haystack {
		if needle == val {
			return true
		}
	}
	return false
}

// Convert []interface{} into []uint64 if possible
func As(slice []interface{}) (res []uint64, err error) {
	res = make([]uint64, len(slice))
	for i := range slice {
		if strVal, ok := slice[i].(uint64); !ok {
			return res, ErrInterfaceNotUint64
		} else {
			res[i] = strVal
		}
	}
	return
}

// Convert []uint64 into []interface{}
func Interface(slice []uint64) (res []interface{}, err error) {
	res = make([]interface{}, len(slice))
	for i := range slice {
		res[i] = slice[i]
	}
	return
}

// func Remove(slice *[]uint64, values ...uint64) (res []uint64) {
// 
// }
// 
// func Replace(slice *[]uint64, val uint64, replacement uint64) (res []uint64) {
// 
// }
// 
// func ReplaceAll(slice *[]uint64, val uint64, replacement uint64) (res []uint64) {
// 
// }
// 
// func IndexOf(haystack []uint64, needle uint64) int {
// 
// }

