// Code generated by z. DO NOT EDIT.

package zint64s

import (
  "errors"
  "sort"
  
)

var (
	ErrInterfaceNotInt64 = errors.New("encountered non-int64 interface")
)

// Determine if two slices are equal to each other
func Equal(a []int64, b []int64) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// Sort the slice in ascending order
func Sort(s []int64) {
  sort.Slice(s, func (i, j int) bool {
    return s[j] > s[i]
  })
}

// Sort the slice in descending order
func SortReverse(s []int64) {
  sort.Slice(s, func (i, j int) bool {
    return s[i] > s[j]
  })
}

// Resize a slice to the given length
func Resize(s []int64, n int) (res []int64) {
  diff := n - len(s)
  if diff > 0 {
    return append(s, make([]int64, diff)...)
  } else {
    return s[:n]
  }
}


// Check if a slice ([]int64) contains a matching member
func Contains(haystack []int64, needle int64) bool {
	for _, val := range haystack {
		if needle == val {
			return true
		}
	}
	return false
}

// Check if a []int64 slice contains ANY of the provided members
func ContainsAny(haystack []int64, needles ...int64) bool {
	for _, needle := range needles {
		if Contains(haystack, needle) {
			return true
		}
	}
	return false
}

// Check if a []int64 slice contains ALL of the provided members
func ContainsAll(haystack []int64, needles ...int64) bool {
	for _, needle := range needles {
		if !Contains(haystack, needle) {
			return false
		}
	}
	return true
}

// Convert a []interface{} slice into []int64 slice if possible
func As(slice []interface{}) (res []int64, err error) {
	res = make([]int64, len(slice))
	for i := range slice {
		if strVal, ok := slice[i].(int64); !ok {
			return res, ErrInterfaceNotInt64
		} else {
			res[i] = strVal
		}
	}
	return
}

// Convert a []int64 slice into a slice of interfaces ([]interface{})
func Interface(slice []int64) (res []interface{}, err error) {
	res = make([]interface{}, len(slice))
	for i := range slice {
		res[i] = slice[i]
	}
	return
}

// Find the index where the needle appears. Returns -1 if the needle doesn't
// appear in the slice.
func Index(haystack []int64, needle int64) int {
	for i := range haystack {
		if haystack[i] == needle {
			return i
		}
	}
	return -1
}

// Cut the slice into two slices separated by the separator
func Cut(slice []int64, separator int64) (left, right []int64, found bool) {
	if i := Index(slice, separator); i >= 0 {
		return slice[:i], slice[i+1:], true
	}
	return slice, nil, false
}

// Cut the slice into two slices separated by the first separator
func CutAny(val []int64, seperators ...int64) (left, right []int64, found bool) {
	for _, sep := range seperators {
		left, right, found = Cut(val, sep)
		if found {
			return
		}
	}
	return
}

// Split the slice into one or more slices separated by the separator
func Split(slice []int64, separator int64) (parts [][]int64) {
	prevI := 0
	for i := range slice {
		if slice[i] == separator {
			if i > prevI {
				parts = append(parts, slice[prevI:i])
			}
			prevI = i + 1
		}
	}
	if len(slice) > prevI {
		parts = append(parts, slice[prevI:])
	}
	return
}

// // Split the slice into one or more slices using multiple separators
// func SplitMany(slice []int64, seperators ...int64) (parts [][]int64) {
// 	parts = append(parts, slice)
// 	for _, sep := range seperators {
// 		for i, part := range parts {
// 			vals := Split(part, sep)
// 			if len(vals) > 1 {
// 				// Replace existing element with all vals
// 				parts = append(parts[:i], append(vals, parts[i+1:]...)...)
// 			}
// 		}
// 	}
// 	return
// }

// // Merge two slices together without repeating values
// func Merge(a []int64, b []int64) (res []int64) {
//
// }

// // Remove the first occurrence of each value from the slice starting from the
// // supplied offset
// func Remove(slice []int64, values ...int64, offset int) (res []int64) {
//
// }

// // Replace the first occurrence of a value with the replacement value
// func Replace(slice []int64, val int64, replacement int64) (res []int64) {
//
// }

// // Replace all occurrences of a value with the replacement value
// func ReplaceAll(slice []int64, val int64, replacement int64) (res []int64) {
//
// }
//
