// Code generated by z. DO NOT EDIT.

package zbytes

func New(items... byte) (s *Set) {
	s = &Set{
		items: make(map[byte]bool),
	}
  s.Add(items...)
  return
}

type Set struct {
	items map[byte]bool
}

func (s *Set) Add(items ...byte) {
	for _, item := range items {
		s.items[item] = true
	}
}

func (s Set) Contains(item byte) bool {
  _, exists := s.items[item]
	return exists
}

func (s Set) ContainsAll(items ...byte) bool {
	for _, item := range items {
		if _, exists := s.items[item]; !exists {
			return false
		}
	}
	return true
}

func (s Set) ContainsAny(items ...byte) bool {
	for _, item := range items {
		if _, exists := s.items[item]; exists {
			return true
		}
	}
	return false
}

func (s *Set) Delete(items ...byte) {
	for _, item := range items {
		delete(s.items, item)
	}
}

func (s *Set) Clear() {
	s.items = make(map[byte]bool)
}

func (s *Set) Size() int {
	return len(s.items)
}

func (s *Set) Items() (res []byte) {
	for key := range s.items {
		res = append(res, key)
	}
	return
}

func (s *Set) Union(others ...Set) {
	for _, b := range others {
		for key := range b.items {
			s.items[key] = true
		}
	}
}

func (s *Set) Complement(others ...Set) {
	for _, b := range others {
		for key := range b.items {
			delete(s.items, key)
		}
	}
}

func (s *Set) Clone() *Set {
	res := New()
	res.Add(s.Items()...)
	return res
}
