// Code generated by z. DO NOT EDIT.

package zint

import "errors"

var (
	ErrInterfaceNotInt = errors.New("encountered non-int interface")
)

// Check if a slice ([]int) contains a matching member
func Contains(haystack []int, needle int) bool {
	for _, val := range haystack {
		if needle == val {
			return true
		}
	}
	return false
}

// Convert []interface{} into []int if possible
func As(slice []interface{}) (res []int, err error) {
	res = make([]int, len(slice))
	for i := range slice {
		if strVal, ok := slice[i].(int); !ok {
			return res, ErrInterfaceNotInt
		} else {
			res[i] = strVal
		}
	}
	return
}

// Convert []int into []interface{}
func Interface(slice []int) (res []interface{}, err error) {
	res = make([]interface{}, len(slice))
	for i := range slice {
		res[i] = slice[i]
	}
	return
}

// func Remove(slice *[]int, values ...int) (res []int) {
// 
// }
// 
// func Replace(slice *[]int, val int, replacement int) (res []int) {
// 
// }
// 
// func ReplaceAll(slice *[]int, val int, replacement int) (res []int) {
// 
// }
// 
// func IndexOf(haystack []int, needle int) int {
// 
// }

