// Code generated by z. DO NOT EDIT.

package zintset

func New() *IntSet {
	return &IntSet{
		items: make(map[int]bool),
	}
}

type IntSet struct {
	items map[int]bool
}

func (s *IntSet) Add(items ...int) {
	for _, item := range items {
		s.items[item] = true
	}
}

func (s IntSet) Contains(items ...int) bool {
	for _, item := range items {
		if _, exists := s.items[item]; !exists {
			return false
		}
	}
	return true
}

func (s *IntSet) Delete(items ...int) {
	for _, item := range items {
		delete(s.items, item)
	}
}

func (s *IntSet) Clear() {
	s.items = make(map[int]bool)
}

func (s *IntSet) Size() int {
	return len(s.items)
}

func (s *IntSet) Items() (res []int) {
	for key := range s.items {
		res = append(res, key)
	}
	return
}

func (s *IntSet) Union(others ...IntSet) {
	for _, b := range others {
		for key := range b.items {
			s.items[key] = true
		}
	}
}

func (s *IntSet) Complement(others ...IntSet) {
	for _, b := range others {
		for key := range b.items {
			delete(s.items, key)
		}
	}
}

func (s *IntSet) Clone() *IntSet {
	res := New()
	res.Add(s.Items()...)
	return res
}
