// Code generated by z. DO NOT EDIT.

package zfloat64set

func New() *Set {
	return &Set{
		items: make(map[float64]bool),
	}
}

type Set struct {
	items map[float64]bool
}

func (s *Set) Add(items ...float64) {
	for _, item := range items {
		s.items[item] = true
	}
}

func (s Set) Contains(items ...float64) bool {
	for _, item := range items {
		if _, exists := s.items[item]; !exists {
			return false
		}
	}
	return true
}

func (s *Set) Delete(items ...float64) {
	for _, item := range items {
		delete(s.items, item)
	}
}

func (s *Set) Clear() {
	s.items = make(map[float64]bool)
}

func (s *Set) Size() int {
	return len(s.items)
}

func (s *Set) Items() (res []float64) {
	for key := range s.items {
		res = append(res, key)
	}
	return
}

func (s *Set) Union(others ...Set) {
	for _, b := range others {
		for key := range b.items {
			s.items[key] = true
		}
	}
}

func (s *Set) Complement(others ...Set) {
	for _, b := range others {
		for key := range b.items {
			delete(s.items, key)
		}
	}
}

func (s *Set) Clone() *Set {
	res := New()
	res.Add(s.Items()...)
	return res
}
