// Code generated by z. DO NOT EDIT.

package zint16set

func New() *Int16Set {
	return &Int16Set{
		items: make(map[int16]bool),
	}
}

type Int16Set struct {
	items map[int16]bool
}

func (s *Int16Set) Add(items ...int16) {
	for _, item := range items {
		s.items[item] = true
	}
}

func (s Int16Set) Contains(items ...int16) bool {
	for _, item := range items {
		if _, exists := s.items[item]; !exists {
			return false
		}
	}
	return true
}

func (s *Int16Set) Delete(items ...int16) {
	for _, item := range items {
		delete(s.items, item)
	}
}

func (s *Int16Set) Clear() {
	s.items = make(map[int16]bool)
}

func (s *Int16Set) Size() int {
	return len(s.items)
}

func (s *Int16Set) Items() (res []int16) {
	for key := range s.items {
		res = append(res, key)
	}
	return
}

func (s *Int16Set) Union(others ...Int16Set) {
	for _, b := range others {
		for key := range b.items {
			s.items[key] = true
		}
	}
}

func (s *Int16Set) Complement(others ...Int16Set) {
	for _, b := range others {
		for key := range b.items {
			delete(s.items, key)
		}
	}
}

func (s *Int16Set) Clone() *Int16Set {
	res := New()
	res.Add(s.Items()...)
	return res
}
