// Code generated by z. DO NOT EDIT.

package zfloat32

import "errors"

var (
	ErrInterfaceNotFloat32 = errors.New("encountered non-float32 interface")
)

// Check if a slice ([]float32) contains a matching member
func Contains(haystack []float32, needle float32) bool {
	for _, val := range haystack {
		if needle == val {
			return true
		}
	}
	return false
}

// Convert []interface{} into []float32 if possible
func As(slice []interface{}) (res []float32, err error) {
	res = make([]float32, len(slice))
	for i := range slice {
		if strVal, ok := slice[i].(float32); !ok {
			return res, ErrInterfaceNotFloat32
		} else {
			res[i] = strVal
		}
	}
	return
}

// Convert []float32 into []interface{}
func Interface(slice []float32) (res []interface{}, err error) {
	res = make([]interface{}, len(slice))
	for i := range slice {
		res[i] = slice[i]
	}
	return
}

// func Remove(slice *[]float32, values ...float32) (res []float32) {
// 
// }
// 
// func Replace(slice *[]float32, val float32, replacement float32) (res []float32) {
// 
// }
// 
// func ReplaceAll(slice *[]float32, val float32, replacement float32) (res []float32) {
// 
// }
// 
// func IndexOf(haystack []float32, needle float32) int {
// 
// }

