// Code generated by z. DO NOT EDIT.

package zuint32set

func New() *Uint32Set {
	return &Uint32Set{
		items: make(map[uint32]bool),
	}
}

type Uint32Set struct {
	items map[uint32]bool
}

func (s *Uint32Set) Add(items ...uint32) {
	for _, item := range items {
		s.items[item] = true
	}
}

func (s Uint32Set) Contains(items ...uint32) bool {
	for _, item := range items {
		if _, exists := s.items[item]; !exists {
			return false
		}
	}
	return true
}

func (s *Uint32Set) Delete(items ...uint32) {
	for _, item := range items {
		delete(s.items, item)
	}
}

func (s *Uint32Set) Clear() {
	s.items = make(map[uint32]bool)
}

func (s *Uint32Set) Size() int {
	return len(s.items)
}

func (s *Uint32Set) Items() (res []uint32) {
	for key := range s.items {
		res = append(res, key)
	}
	return
}

func (s *Uint32Set) Union(others ...Uint32Set) {
	for _, b := range others {
		for key := range b.items {
			s.items[key] = true
		}
	}
}

func (s *Uint32Set) Complement(others ...Uint32Set) {
	for _, b := range others {
		for key := range b.items {
			delete(s.items, key)
		}
	}
}

func (s *Uint32Set) Clone() *Uint32Set {
	res := New()
	res.Add(s.Items()...)
	return res
}
