// Code generated by z. DO NOT EDIT.

package zuint64s

import (
  "errors"
  "sort"
  
)

var (
	ErrInterfaceNotUint64 = errors.New("encountered non-uint64 interface")
)

// Determine if two slices are equal to each other
func Equal(a []uint64, b []uint64) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// Sort the slice in ascending order
func Sort(s []uint64) {
  sort.Slice(s, func (i, j int) bool {
    return s[j] > s[i]
  })
}

// Sort the slice in descending order
func SortReverse(s []uint64) {
  sort.Slice(s, func (i, j int) bool {
    return s[i] > s[j]
  })
}

// Resize a slice to the given length
func Resize(s []uint64, n int) (res []uint64) {
  diff := n - len(s)
  if diff > 0 {
    return append(s, make([]uint64, diff)...)
  } else {
    return s[:n]
  }
}


// Check if a slice ([]uint64) contains a matching member
func Contains(haystack []uint64, needle uint64) bool {
	for _, val := range haystack {
		if needle == val {
			return true
		}
	}
	return false
}

// Check if a []uint64 slice contains ANY of the provided members
func ContainsAny(haystack []uint64, needles ...uint64) bool {
	for _, needle := range needles {
		if Contains(haystack, needle) {
			return true
		}
	}
	return false
}

// Check if a []uint64 slice contains ALL of the provided members
func ContainsAll(haystack []uint64, needles ...uint64) bool {
	for _, needle := range needles {
		if !Contains(haystack, needle) {
			return false
		}
	}
	return true
}

// Convert a []interface{} slice into []uint64 slice if possible
func As(slice []interface{}) (res []uint64, err error) {
	res = make([]uint64, len(slice))
	for i := range slice {
		if strVal, ok := slice[i].(uint64); !ok {
			return res, ErrInterfaceNotUint64
		} else {
			res[i] = strVal
		}
	}
	return
}

// Convert a []uint64 slice into a slice of interfaces ([]interface{})
func Interface(slice []uint64) (res []interface{}, err error) {
	res = make([]interface{}, len(slice))
	for i := range slice {
		res[i] = slice[i]
	}
	return
}

// Find the index where the needle appears. Returns -1 if the needle doesn't
// appear in the slice.
func Index(haystack []uint64, needle uint64) int {
	for i := range haystack {
		if haystack[i] == needle {
			return i
		}
	}
	return -1
}

// Cut the slice into two slices separated by the separator
func Cut(slice []uint64, separator uint64) (left, right []uint64, found bool) {
	if i := Index(slice, separator); i >= 0 {
		return slice[:i], slice[i+1:], true
	}
	return slice, nil, false
}

// Cut the slice into two slices separated by the first separator
func CutAny(val []uint64, seperators ...uint64) (left, right []uint64, found bool) {
	for _, sep := range seperators {
		left, right, found = Cut(val, sep)
		if found {
			return
		}
	}
	return
}

// Split the slice into one or more slices separated by the separator
func Split(slice []uint64, separator uint64) (parts [][]uint64) {
	prevI := 0
	for i := range slice {
		if slice[i] == separator {
			if i > prevI {
				parts = append(parts, slice[prevI:i])
			}
			prevI = i + 1
		}
	}
	if len(slice) > prevI {
		parts = append(parts, slice[prevI:])
	}
	return
}

// // Split the slice into one or more slices using multiple separators
// func SplitMany(slice []uint64, seperators ...uint64) (parts [][]uint64) {
// 	parts = append(parts, slice)
// 	for _, sep := range seperators {
// 		for i, part := range parts {
// 			vals := Split(part, sep)
// 			if len(vals) > 1 {
// 				// Replace existing element with all vals
// 				parts = append(parts[:i], append(vals, parts[i+1:]...)...)
// 			}
// 		}
// 	}
// 	return
// }

// // Merge two slices together without repeating values
// func Merge(a []uint64, b []uint64) (res []uint64) {
//
// }

// Remove the first occurrence of each value from the slice starting from the
// supplied offset
func Remove(slice []uint64, offset int, values ...uint64) (res []uint64) {
  for i := offset; i < len(slice); i++ {
    for _, val := range values {
      if slice[i] == val {
        break
      }
      res = append(res, slice[i])
    }
  }
  return
}

// Remove the item at the index while preserving the order of the items
// TODO: maybe change this to take multiple indices and to remove them at the 
// same time
func RemoveAt(slice []uint64, index int) (res []uint64) {
  if index >= len(slice) {
    panic("index cannot be greater than len(slice)")
  } else if index == len(slice) - 1 {
    res = slice[:index]
  } else {
    res = append(slice[:index], slice[index+1:]...)
  }
  return
}

// // Replace the first occurrence of a value with the replacement value
// func Replace(slice []uint64, val uint64, replacement uint64) (res []uint64) {
//
// }

// // Replace all occurrences of a value with the replacement value
// func ReplaceAll(slice []uint64, val uint64, replacement uint64) (res []uint64) {
//
// }
//
